### ISSUE TITLE
Host Vulcan in container

### ISSUE THREAD

**Issue by XanderVertegaal** [CentreForDigitalHumanities/parseport#66]
Vulcan needs to be hosted in its own container and hooked up to the backend server.

More specifically:
- write Dockerfile that builds the Vulcan container;
- write backend views that accept input from frontend
- sanitize input and send to Vulcan container
- retrieve HTML + JS in backend

**Comment by megodoonch** [comment]
I don't know if you can tell from the Vulcan code and/or documentation whether it's already run in a container. If not, Jonas Groschwitz (the Vulcan guy) should be able to tell you.
